import Vue from 'vue';
import ElementUI from 'element-ui';
import VueRouter from 'vue-router';
import axios from 'axios';
import Vuex from 'vuex';
import Cookies from 'js-cookie';
import clipboard from 'clipboard';
import html2canvas from 'html2canvas';
import rasterizehtml from 'rasterizehtml';
